# Generated by Django 5.0.6 on 2026-06-29 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('commander', 'Commander / EDH'), ('standard', 'Standard'), ('modern', 'Modern'), ('pioneer', 'Pioneer'), ('pauper', 'Pauper'), ('legacy', 'Legacy'), ('other', 'Other')], default='commander', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands_decks', to='cards.card')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_owned', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deck_entries', to='cards.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='decks.deck')),
            ],
            options={
                'ordering': ['card__name'],
                'unique_together': {('deck', 'card')},
            },
        ),
    ]
