# Generated by Django 5.0.6 on 2026-06-29 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('oracle_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('scryfall_id', models.CharField(blank=True, max_length=64)),
                ('set_code', models.CharField(blank=True, db_index=True, max_length=16)),
                ('set_name', models.CharField(blank=True, max_length=128)),
                ('type_line', models.CharField(blank=True, max_length=255)),
                ('primary_type', models.CharField(blank=True, db_index=True, max_length=32)),
                ('colors', models.CharField(blank=True, max_length=5)),
                ('color_identity', models.CharField(blank=True, max_length=5)),
                ('rarity', models.CharField(blank=True, db_index=True, max_length=16)),
                ('mana_value', models.FloatField(default=0)),
                ('image_uri', models.URLField(blank=True, max_length=500)),
                ('scryfall_uri', models.URLField(blank=True, max_length=500)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_usd_foil', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
                ('in_vault', models.BooleanField(db_index=True, default=False)),
                ('added_to_vault_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('color', models.CharField(blank=True, default='slate', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CardTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_tags', to='cards.card')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_cards', to='cards.tag')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('card', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cards', through='cards.CardTag', to='cards.tag'),
        ),
    ]
