# Generated by Django 5.0.6 on 2026-06-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_collector_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='card',
            name='suggested_commanders',
            field=models.ManyToManyField(blank=True, related_name='suggested_cards', to='cards.card'),
        ),
    ]
