# Generated by Django 5.0.6 on 2026-06-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_notes_card_suggested_commanders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default='#64748b', max_length=7),
        ),
    ]
