# Generated by Django 5.0.6 on 2026-07-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_backfill_tag_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_uri_back',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='card',
            name='layout',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
